# Generated by Django 5.1 on 2024-08-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobrade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cobrade_id', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
