# Generated by Django 5.1 on 2024-08-28 04:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_cobrade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolForm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cobrade_detail', models.CharField(blank=True, max_length=255)),
                ('initial_date', models.DateField()),
                ('final_date', models.DateField(blank=True, null=True)),
                ('statusForm', models.CharField(default='Criado', max_length=50)),
                ('id_fide', models.CharField(blank=True, max_length=20)),
                ('age_range_form', models.JSONField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, max_length=50)),
                ('raca', models.CharField(blank=True, max_length=50)),
                ('escolaridade', models.CharField(blank=True, max_length=50)),
                ('tipos_danos', models.JSONField(blank=True, null=True)),
                ('qtd_alunos_mortos', models.CharField(blank=True, max_length=50)),
                ('qtd_alunos_feridos', models.CharField(blank=True, max_length=50)),
                ('qtd_alunos_desalojados', models.CharField(blank=True, max_length=50)),
                ('qtd_alunos_desabrigados', models.CharField(blank=True, max_length=50)),
                ('qtd_alunos_doentes', models.CharField(blank=True, max_length=50)),
                ('qtd_alunos_traumas_psicologicos', models.CharField(blank=True, max_length=50)),
                ('qtd_servidores_mortos', models.CharField(blank=True, max_length=50)),
                ('qtd_servidores_feridos', models.CharField(blank=True, max_length=50)),
                ('qtd_servidores_desalojados', models.CharField(blank=True, max_length=50)),
                ('qtd_servidores_desabrigados', models.CharField(blank=True, max_length=50)),
                ('qtd_servidores_doentes', models.CharField(blank=True, max_length=50)),
                ('qtd_servidores_traumas_psicologicos', models.CharField(blank=True, max_length=50)),
                ('cobrade_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.cobrade')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.school')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
